import React from "react";
import {
  Card,
  CardContent,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableRow,
  TableContainer,
  Paper,
  Box,
  Stack,
  Divider,
} from "@mui/material";

type PredictionResultProps = {
  result: {
    prediction: string;
    lower_bound: string;
    upper_bound: string;
  };
};

const PredictionResult: React.FC<PredictionResultProps> = ({ result }) => {
  const getLabel = (prediction: string) => {
    switch (prediction.toLowerCase()) {
      case "positive deal":
        return "Slightly Positive";
      case "negative deal":
        return "Slightly Negative";
      case "neutral deal":
        return "Neutral";
      default:
        return prediction;
    }
  };

  const getColor = (prediction: string) => {
    switch (prediction.toLowerCase()) {
      case "positive deal":
        return "#2e7d32"; // Green
      case "negative deal":
        return "#c62828"; // Red
      case "neutral deal":
        return "#ef6c00"; // Orange
      default:
        return "#333";
    }
  };

  const color = getColor(result.prediction);

  return (
    <Card
      variant="outlined"
      sx={{
        width: "100%",
        maxWidth: 480,
        mx: "auto",
        boxShadow: 4,
        borderRadius: 3,
        backgroundColor: "#ffffff",
      }}
    >
      <CardContent>
        <Stack spacing={2}>
        <Typography variant="body1" color="text.primary">
          Results are generated by a machine learning model trained on historical data to estimate outlook and confidence range based on current conditions.
          </Typography>

          <Divider />

          <Typography variant="h6" sx={{ color }}>
            Prediction Summary
          </Typography>

          <TableContainer component={Paper} elevation={0}>
            <Table size="small">
              <TableBody>
                <TableRow>
                  <TableCell
                    sx={{
                      fontWeight: 600,
                      backgroundColor: "#e3f2fd",
                      // width: "50%",
                    }}
                  >
                    Expected to Provide
                  </TableCell>
                  <TableCell sx={{ color }}>{getLabel(result.prediction)}</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell sx={{ fontWeight: 600, backgroundColor: "#e3f2fd" }}>
                    High Confidence Return Range
                  </TableCell>
                  <TableCell sx={{ color }}>
                    {result.lower_bound}% to {result.upper_bound}%
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TableContainer>
        </Stack>
      </CardContent>
    </Card>
  );
};

export default PredictionResult;
